//
// AccessTokenRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AccessTokenRequest: Codable, JSONEncodable, Hashable {

    public enum GrantType: String, Codable, CaseIterable {
        case refreshToken = "refresh_token"
    }
    public var grantType: GrantType
    public var refreshToken: String

    public init(grantType: GrantType, refreshToken: String) {
        self.grantType = grantType
        self.refreshToken = refreshToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case grantType = "grant_type"
        case refreshToken = "refresh_token"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(grantType, forKey: .grantType)
        try container.encode(refreshToken, forKey: .refreshToken)
    }
}

