//
// DeviceInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeviceInfo: Codable, JSONEncodable, Hashable {

    public var type: DeviceType
    public var info: [String: String]

    public init(type: DeviceType, info: [String: String]) {
        self.type = type
        self.info = info
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case info
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(info, forKey: .info)
    }
}

