//
// DeviceType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum DeviceType: String, Codable, CaseIterable {
    case ios = "ios"
    case ipados = "ipados"
    case watchos = "watchos"
    case macos = "macos"
    case android = "android"
    case wp = "wp"
    case other = "other"
}
