name: ForestVPNCloudSDKAPI
targets:
  ForestVPNCloudSDKAPI:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [ForestVPNCloudSDKAPIClient/Classes]
    info:
      path: ./Info.plist
      version: 0.1.1
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
